### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by wgtoliveira** [subutux/ulauncher-variety#1]
The extension exited instantly. Please check the logs.

You can let the author know about this problem by creating a Github issue.

**Comment by subutux** [comment]
Hey @wgtoliveira 

Do you have variety running?

**Comment by subutux** [comment]
Hey @wgtoliveira,
Might this be related to the (in)famous GTK4 Issue Ulauncher/Ulauncher#703 ?
if so, might I suggest using the https://github.com/friday/Ulauncher-Revived project instead?  It seems that the original developer of ULauncher vanished and is not responding to any communications.

if you still are having issues, please don't hesitate to open a new issue!
